Milesone6:
Ambrosegithub/My-porfolio pull request #11
Opened 2022-06-23 14:34 UTC by Ambrosegithub

## modal pop up window

- add js file.
- display the modal window using javascript.
- add images. 
- receive contribution from partners

2022-06-23 14:49 UTC, muneebulrehman requested changes
Hi @Ambrosegithub , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 14:49 UTC, muneebulrehman commented on index.html
> + <section id="project-sections">
The whole projects section should be generated dynamically using Javascript. Kindly update this section accordingly.

2022-06-23 14:49 UTC, muneebulrehman commented on index.html
> + <section id="project-sections">
Also, this whole section is a mess in desktop view. Have a look at the below screenshots. Kindly fix it and check it thoroughly before asking for another review.
![image](https://user-images.githubusercontent.com/33268927/175326739-9a0866f1-7a4d-43dd-99f2-272dbfb3f5b8.png)
![image](https://user-images.githubusercontent.com/33268927/175326819-9949cb95-93b7-4287-b06e-3cfc7542824e.png)

2022-06-23 14:49 UTC, muneebulrehman commented on index.html
> +    <!--modal pop up ends here-->
Your model should also be generated dynamically using Javascript. Kindly update this section also.
Also, your model is spanning more than two pages vertically, and margins, padding, spacing, and positioning need to be almost exactly like the Figma template of your choosing. Kindly make it according to your Figma design.

2022-06-25 17:27 UTC, danielufeli approved these changes
Hi @Ambrosegithub ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 17:30 UTC, merged